
INSERT INTO users (username, email, password1, full_name, eco_points, points, reason, bio) VALUES
('john_doe', 'john@example.com', 'password1', 'John Doe', 100, 45, 'Reason for John Doe', 'Bio for John Doe'),
('jane_doe', 'jane@example.com', 'password2', 'Jane Doe', 100, 32, 'Reason for Jane Doe', 'Bio for Jane Doe'),
('alice', 'alice@example.com', 'password3', 'Alice Wonderland', 100, 78, 'Reason for Alice Wonderland', 'Bio for Alice Wonderland'),
('bob', 'bob@example.com', 'password4', 'Bob Builder', 100, 67, 'Reason for Bob Builder', 'Bio for Bob Builder'),
('charlie', 'charlie@example.com', 'password5', 'Charlie Brown', 100, 54, 'Reason for Charlie Brown', 'Bio for Charlie Brown'),
('dave', 'dave@example.com', 'password6', 'Dave Grohl', 100, 29, 'Reason for Dave Grohl', 'Bio for Dave Grohl'),
('eve', 'eve@example.com', 'password7', 'Eve Polastri', 100, 72, 'Reason for Eve Polastri', 'Bio for Eve Polastri'),
('frank', 'frank@example.com', 'password8', 'Frank Sinatra', 100, 68, 'Reason for Frank Sinatra', 'Bio for Frank Sinatra'),
('grace', 'grace@example.com', 'password9', 'Grace Hopper', 100, 44, 'Reason for Grace Hopper', 'Bio for Grace Hopper'),
('heidi', 'heidi@example.com', 'password10', 'Heidi Klum', 100, 15, 'Reason for Heidi Klum', 'Bio for Heidi Klum'),
('ivan', 'ivan@example.com', 'password11', 'Ivan Drago', 100, 28, 'Reason for Ivan Drago', 'Bio for Ivan Drago'),
('judy', 'judy@example.com', 'password12', 'Judy Garland', 100, 74, 'Reason for Judy Garland', 'Bio for Judy Garland'),
('mallory', 'mallory@example.com', 'password13', 'Mallory Archer', 100, 53, 'Reason for Mallory Archer', 'Bio for Mallory Archer'),
('nancy', 'nancy@example.com', 'password14', 'Nancy Drew', 100, 36, 'Reason for Nancy Drew', 'Bio for Nancy Drew'),
('oscar', 'oscar@example.com', 'password15', 'Oscar Wilde', 100, 42, 'Reason for Oscar Wilde', 'Bio for Oscar Wilde'),
('peggy', 'peggy@example.com', 'password16', 'Peggy Carter', 100, 59, 'Reason for Peggy Carter', 'Bio for Peggy Carter'),
('trent', 'trent@example.com', 'password17', 'Trent Reznor', 100, 62, 'Reason for Trent Reznor', 'Bio for Trent Reznor'),
('sybil', 'sybil@example.com', 'password18', 'Sybil Trelawney', 100, 34, 'Reason for Sybil Trelawney', 'Bio for Sybil Trelawney'),
('victor', 'victor@example.com', 'password19', 'Victor Frankenstein', 100, 18, 'Reason for Victor Frankenstein', 'Bio for Victor Frankenstein'),
('walter', 'walter@example.com', 'password20', 'Walter White', 100, 77, 'Reason for Walter White', 'Bio for Walter White');
